-- batto configuration
-- Edit this file to customize batto.

-- batto.setup({
--   window = {
--     width = 600,
--     list_height = 300,
--     icon_size = 48,
--     hide_on_blur = true, -- hide window when focus is lost
--   },
--   keys = {
--     accept = "enter",
--     close = "escape",
--     up = "up",
--     down = "down",
--     tab_complete = "tab",
--   },
-- })

-- Example command (type / to enter command mode):
-- batto.command({
--   name = "search",
--   description = "Search the web",
--   args = {
--     { name = "query", required = true, type = "string" },
--   },
--   exec = "xdg-open 'https://google.com/search?q={{args}}'",
-- })

-- Plugins (place in ~/.config/batto/plugins/<name>/init.lua):
-- batto.use("web-search")
-- batto.use("notion")
